apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: spring-test-nov13 
  janus-idp.io/tekton: spring-test-nov13
  backstage.io/kubernetes-id: spring-test-nov13
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: spring-test-nov13
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  