apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: spring-test-nov13
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring-test-nov13 
  name: spring-test-nov13
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: spring-test-nov13 
